services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: linuxserver-swag
    cap_add:
      - NET_ADMIN
    env_file:
      - ./swag/.env
    volumes:
      - ./swag/config:/config
      - /home/nas/nvme/share/donghun/documents/resume/_latest:/static_files
    ports:
      - 444:443
      - 81:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  certbot:
    build:
      context: ./certbot
    container_name: linuxserver-certbot
    restart: unless-stopped
    env_file:
      - ./certbot/.env
    volumes:
      - ./swag/config/etc/letsencrypt:/etc/letsencrypt
      - ./swag/config/dns-conf/cloudflare.ini:/etc/cloudflare/cloudflare.ini
      - ./certbot/www:/var/www/certbot

  # habridge:
  #   image: lscr.io/linuxserver/habridge:latest
  #   container_name: linuxserver-habridge
  #   env_file:
  #     - ./habridge/.env
  #   volumes:
  #     - ./habridge/config:/config
  #   ports:
  #     - 8010:8080
  #     - 50000:50000
  #   restart: unless-stopped
