services:
  homeassistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeassistant
    env_file:
      - .env
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./libhueble/src:/usr/src/app/src
      - ./libhueble/scripts:/usr/src/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock 
    restart: unless-stopped
    privileged: true
    network_mode: host
  hueble:
    build:
      context: ./libhueble
      dockerfile: Dockerfile
    container_name: hueble
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./libhueble/src:/usr/src/app/src
      - ./libhueble/scripts:/usr/src/app/scripts
    restart: unless-stopped
    privileged: true
    network_mode: host

  motion_recorder:
    build:
      context: ./motion_recorder
      dockerfile: Dockerfile
    container_name: motion_recorder
    env_file:
      - .env
    volumes:
      - /home/nas/nvme/share/nas/tmp/motion_recorder/recordings:/recordings
    restart: unless-stopped
