'1':
  name: Daylight
  id_v1: '1'
  id_v2: 03ee03b6-e491-4f32-9325-222e6a99cc60
  state:
    daylight: null
    lastupdated: none
  config:
    'on': true
    configured: false
    sunriseoffset: 30
    sunsetoffset: -30
    reachable: true
  type: Daylight
  modelid: PHDL00
  manufacturername: Signify Netherlands B.V.
  uniqueid: null
  swversion: '1.0'
  protocol: none
  protocol_cfg: {}
