services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./stirling/trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - ./stirling/extraConfigs:/configs
      - ./stirling/customFiles:/customFiles/
      - ./stirling/logs:/logs/
    env_file:
    - .env
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
    ports:
      - "8001:8080"
    restart: unless-stopped
